name: build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSVC with vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg

      - name: Install dependencies
        run: |
          vcpkg install cpprestsdk cpprestsdk:x64-windows

      - name: Configure CMake
        run: cmake --preset=default

      - name: Build project
        run: cmake --build build
